name: CI
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8.0-rc1'

      - name: Run Pluto notebooks
        run: julia -e 'using Pkg;
            Pkg.activate(".");
            Pkg.instantiate();
            using PlutoSliderServer;
            for file in readdir("notebooks")
              endswith(file, ".jl") && PlutoSliderServer.export_notebook(joinpath("notebooks", file))
            end
            '
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: .
