name: CI
on:
  - push
  - pull_request
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: Run Pluto notebooks
        run: julia -e 'using Pkg;
            Pkg.activate(".");
            Pkg.instantiate();
            Pkg.add([
            Pkg.PackageSpec(url="https://github.com/GiggleLiu/PlutoUtils.jl", rev="static-export"),
            Pkg.PackageSpec(url="https://github.com/fonsp/Pluto.jl", rev="05e5b68"),
            ]);
            import PlutoUtils;
            PlutoUtils.Export.github_action(; notebook_dir=joinpath(@__DIR__, "notebooks"), offer_binder=false, export_dir=@__DIR__, generate_default_index=true, project=@__DIR__)
            '
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: .
